image: node:latest

pages:
    script:
        - npm install
        - npm run build
        - mv dist public
    cache:
        paths:
            - node_modules
    artifacts:
        paths:
            - public